version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  heroku_deploy:
    jobs:
      - tests:
          run:
            name: run tests
            command: python testApp.py
      - heroku/deploy-via-git:
        filters:
          branches:
            only: master
